// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAra1jdhI-g5eLRVw3MEYbV56NB_SB9j-s',
    appId: '1:514656901571:web:944a99244e78655c734576',
    messagingSenderId: '514656901571',
    projectId: 'auth-login-f5d5c',
    authDomain: 'auth-login-f5d5c.firebaseapp.com',
    storageBucket: 'auth-login-f5d5c.appspot.com',
    measurementId: 'G-VDKZ0YF70G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7pXPfxlWxtuXHnWhfEbpdjbmbUxtMFrs',
    appId: '1:514656901571:android:bac030885018c2df734576',
    messagingSenderId: '514656901571',
    projectId: 'auth-login-f5d5c',
    storageBucket: 'auth-login-f5d5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ6FCeCUB9dl_brKizm3Spf8k21Bh2Gu0',
    appId: '1:514656901571:ios:84d9c62a4fbb137f734576',
    messagingSenderId: '514656901571',
    projectId: 'auth-login-f5d5c',
    storageBucket: 'auth-login-f5d5c.appspot.com',
    iosClientId: '514656901571-bup5up2llf1238o5pao5i5ff2t7u9btu.apps.googleusercontent.com',
    iosBundleId: 'com.example.authLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ6FCeCUB9dl_brKizm3Spf8k21Bh2Gu0',
    appId: '1:514656901571:ios:84d9c62a4fbb137f734576',
    messagingSenderId: '514656901571',
    projectId: 'auth-login-f5d5c',
    storageBucket: 'auth-login-f5d5c.appspot.com',
    iosClientId: '514656901571-bup5up2llf1238o5pao5i5ff2t7u9btu.apps.googleusercontent.com',
    iosBundleId: 'com.example.authLogin',
  );
}
